#! /bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

runlevel=S

prevlevel=N

umask 022

export PATH runlevel prevlevel


/bin/hostname cyembed

echo "----------rcS----------------"
echo "----------mount all----------"


/bin/mount -a

echo /sbin/mdev>/proc/sys/kernel/hotplug

mdev -s

echo "**************************************"

echo "**************************************"

echo "Kernel version:linux-3.9.6"

echo "Date:2013.12.31"

echo "**************************************"

