apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-env
  namespace: loch
spec:
  containers:
  - name: pod-secret-env
    image: busybox:1.28.4
    args:
      - /bin/sh
      - -c
      - sleep 10;touch /tmp/healthy;sleep 30000
    env:
      - name: SECRET_USERNAME
        valueFrom:
          secretKeyRef:
            name: lochsecret
            key: username
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: lochsecret
            key: password