apiVersion: v1
kind: Pod
metadata:
  name: secret-opaque-env-pod
  namespace: loch
spec:
  containers:
  - name: secret-opaque-env-pod
    image: busybox
    command: [ "/bin/sh", "-c", "env" ]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: opaquesecret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: opaquesecret
          key: password
