apiVersion: v1
kind: Pod
metadata:
  name: secret-opaque-volume
  namespace: loch
spec:
  containers:
  - name: secret2
    image: busybox
    command: ["/bin/sh", "-c", "ls /etc/secrets"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets
    secret:
     secretName: opaquesecret
