/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DIR_H_RPCGEN
#define _RPC_DIR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define PATH_LEN 256

#define DIRPROG 0x30090949
#define DIRVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RMKDIR 1
extern  int * rmkdir_1(char **, CLIENT *);
extern  int * rmkdir_1_svc(char **, struct svc_req *);
#define RRMDIR 2
extern  int * rrmdir_1(char **, CLIENT *);
extern  int * rrmdir_1_svc(char **, struct svc_req *);
extern int dirprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RMKDIR 1
extern  int * rmkdir_1();
extern  int * rmkdir_1_svc();
#define RRMDIR 2
extern  int * rrmdir_1();
extern  int * rrmdir_1_svc();
extern int dirprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_DIR_H_RPCGEN */
