# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
#   namespace: loch
#   labels:
#     app: mysql
# spec:
#   type: NodePort
#   selector:
#       app: mysql
#   ports:
#   - protocol : TCP
#     nodePort: 30306
#     port: 3306
#     targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: loch
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306           # service port
    targetPort: 3306     # container port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: loch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: Never
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "123456"
          - name: MYSQL_USER
            value: "dbuser"
          - name: MYSQL_PASSWORD
            value: "123456"
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
          - containerPort: 3306
            name: mysql
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        # - name: mysql-storage
        #   hostPath:
        #     path: /data/mnt/k8s/mysql
        - name: mysql-storage
          emptyDir: {}

