apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: loch
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "123456"
    - name: MYSQL_USER
      value: "dbuser"
    - name: MYSQL_PASSWORD
      value: "123456"
    resources:
      limits:
        cpu: "0.5"
        memory: 512Mi
      requests:
        cpu: "0.5"
        memory: 512Mi
    livenessProbe:
      exec:
        command: ["mysqladmin", "-uroot", "-p123456", "ping"]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 2
    readinessProbe:
      exec:
        command: ["mysql", "-h", "127.0.0.1","-uroot", "-p123456", "-e", "SELECT 1"]
      initialDelaySeconds: 5
      periodSeconds: 2
      timeoutSeconds: 2
  - name: nginx
    image: nginx
  restartPolicy: Always
