/*
389. Find the Difference

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

#include<vector>
#include<algorithm>
#include<iostream>
#include<string>
#include<unordered_map>

using namespace std;

class Solution
{
public:
    char findTheDifference(string s, string t)
    {
        unordered_map<char, int> m;
        for(auto c : s) {
            m[c] ++;
        }
        for(auto c : t) {
            if(m.find(c) == m.end()) {
                return c;
            }
            if(m.find(c) != m.end()) {
                if(m[c] == 0) {
                    return c;
                }
                m[c]--;
            }
        }
        return '\0';
    }
};


int main()
{
    Solution sln;
    cout << sln.findTheDifference("abcd", "abcde") << endl; // e
    system("pause");
    return 0;
}
