apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.6.0
    jvmOptions:
      "-Xmx": "512m"
      "-Xms": "512m"
    replicas: 3
    listeners:
      plain:
        port: 9092
        tls: false
        type: internal
      external:
        type: nodeport
        port: 9094
        tls: false
        authentication:
          type: scram-sha-512
        overrides:
          brokers:
          - broker: 0
            advertisedHost: nj.kafka-broker-0.domain.com
          - broker: 1
            advertisedHost: nj.kafka-broker-1.domain.com
          - broker: 2
            advertisedHost: nj.kafka-broker-2.domain.com
    authorization:
      type: simple
      superUsers:
        - admin
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
        # class:
    resources:
      reqeusts:
        cpu: 0.3
        memory: 512Mi
      limits:
        cpu: 0.5
        memory: 1024Mi
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    vmOptions:
      "-Xmx": "256m"
      "-Xms": "256m"
    resources:
      reqeusts:
        cpu: 0.3
        memory: 256Mi
      limits:
        cpu: 0.5
        memory: 512Mi
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - zookeeper
                topologyKey: "kubernetes.io/hostname"
  entityOperator:
    topicOperator: {}
    userOperator: {}

