apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: foo
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: foo
          patternType: literal
        operation: All
        host: "*"
      - resource:
          type: group
          name: console-consumer
          patternType: prefix
        operation: Read
        host: "*"