apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readness
  name: readness
  namespace: loch
spec:
  restartPolicy: OnFailure
  containers:
  - name: readness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthcheck;sleep 30; rm -rf /tmp/healthcheck;sleep 600
    readinessProbe:
      # exec is running inside contailner, httpget and tcpsocket probe are running out of pod.
      exec:
        command:
        - cat
        - /tmp/healthcheck
      initialDelaySeconds: 10
      periodSeconds: 5
