---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  namespace: loch
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: kafka-svc
  clusterIP: None
  selector:
    app: kafka

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: loch
spec:
  serviceName: kafka
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
     matchLabels:
        app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - kafka
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 300
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: wurstmeister/kafka:latest
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 9092
          name: server
        env:
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx768M -Xms768M"
        - name: KAFKA_OPTS
          value: "-Dlogging.level=INFO"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-cs:2181
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name 
        
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka
        readinessProbe:
          tcpSocket:
            port: 9092
          timeoutSeconds: 5
          initialDelaySeconds: 10
      initContainers:
      - name: init-zk
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup zk-cs; do echo waiting for zk-cs; sleep 2; done;']
      volumes:
      - name: datadir
        emptyDir: {}
      securityContext:
        runAsUser: 0
