apiVersion: v1
kind: Service
metadata:
  name: airflow
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: airflow
    release: canary
  ports:
  - name: http
    nodePort: 30002
    targetPort: 8080
    port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deploy
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      release: canary
  template:
    metadata:
      labels:
        app: airflow
        release: canary
    spec:
      containers:
      - name: airflow
        image: puckel/docker-airflow:latest
        ports:
        - name: http
          containerPort: 8080
        volumeMounts:
            - mountPath:  /usr/local/airflow/dags
              name: dag
              mountPropagation: "HostToContainer"
      volumes:
        - name: dag
          hostPath:
            path: /opt/data/airflow