apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus
  name: prometheus
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    port: web
    relabelings:
    - targetLabel: region
      replacement: mianyang
  selector:
    matchLabels:
      prometheus: k8s
